feat: [ACADEMIC-16221] Improved content-length using parsed content
edx/ai-aside pull request #24
Opened 2023-06-22 16:52 UTC by rijuma

# [ACADEMIC-16221](https://jira.2u.com/browse/ACADEMIC-16221)

Added 2-stage check on content length. 1st stage checks for summarizable candidates based on the raw length for the html content or the category (video). 2nd stage take these potential elements, extracts/parses the content and then checks again if the content length meets the requirements.

Minor cleanup on a few lines.

2023-06-22 17:03 UTC, germanolleunlp approved these changes

2023-06-23 13:30 UTC, ashultz0 requested changes
👍 to working on the whole content now. There's one more logical change to make that goes with that in the first level check and I think you should make it in this PR.

Also there's one test bug that means the tests are not doing what you expect and of course I have name suggestions you might like.

2023-06-23 13:30 UTC, ashultz0 commented on ai_aside/summaryhook_aside/block.py
> +        'items': content_fragments
items is a better word so you could rename content_fragments content_items

2023-06-23 13:30 UTC, ashultz0 commented on ai_aside/summaryhook_aside/block.py
> +    We don't sanitize the content due to performance in this first check.
(this comment is about the line below I can't comment on directly)

in this line below:
category == 'html' and len(child.get_html()) > settings.SUMMARY_HOOK_MIN_SIZE:

we reject if none of the children has enough html by themselves. Your new code is all about considering the children together and is more correct So I think it makes sense in this PR to instead total up the len(child.get_html).

You could keep a running length and return true immediately once it goes above the length, or just wait and check it after the loop

2023-06-23 13:30 UTC, ashultz0 commented on tests/summaryhook_aside/test_block.py
> +            return fake_transcript
this should be the category video clause right? currently this code will never be reached

2023-06-23 13:30 UTC, ashultz0 commented on tests/summaryhook_aside/test_block.py
> +        self.assertEqual(content, expected)
if expected is just True it's not really worth having a separate variable for it, just do self.assertEqual(content, expected) or even better self.assertTrue(content)

2023-06-23 13:30 UTC, ashultz0 commented on tests/summaryhook_aside/test_block.py
> +        content = _check_summarizable_content(block)
this variable should be "summarizable" not "content" because it's not a bunch of content, it's a boolean

2023-06-23 13:30 UTC, ashultz0 commented on tests/summaryhook_aside/test_block.py
> +        self.assertEqual(content, expected)
same variable name and assert here

2023-06-23 13:48 UTC, ashultz0 commented
oh one other housekeeping thing, we should get in the habit of adding to the changelog in the unreleased section to make releasing easier, there is not an automated tool in this repo yet

https://github.com/edx/ai-aside/blob/main/CHANGELOG.rst

2023-06-27 13:58 UTC, ashultz0 approved these changes

2023-06-27 14:41 UTC, merged