[ACADEMIC-16210] Add endpoints for enabling courses/modules
edx/ai-aside pull request #38
Opened 2023-07-18 14:05 UTC by rijuma

This is a temporary PR. Work in progress.

**Merge checklist:**
Check off if complete *or* not applicable:
- [ ] Version bumped
- [ ] Changelog record added
- [ ] Documentation updated (not only docstrings)
- [ ] Fixup commits are squashed away
- [ ] Unit tests added/updated
- [ ] Manual testing instructions provided
- [ ] Noted any: Concerns, dependencies, migration issues, deadlines, tickets

2023-07-18 16:24 UTC, ashultz0 commented on ai_aside/api/views.py
> +            AIAsideCourseEnabled.objects.create(
probably this should be create or update so that you can post a new one or update an old one

2023-07-19 18:48 UTC, rijuma commented on ai_aside/api/views.py
> +            AIAsideCourseEnabled.objects.create(
Indeed. Updated!

2023-07-19 19:34 UTC, ashultz0 commented on ai_aside/.DS_Store
looks like .DS_Store should be added to gitignore

2023-07-19 19:34 UTC, ashultz0 commented on ai_aside/__init__.py
>  __version__ = '3.0.0'
update version here

2023-07-19 19:35 UTC, rijuma commented on test_settings.py
> +    'django.contrib.auth.middleware.AuthenticationMiddleware',
I swapped the order of these for the tests to work. It seems like the order matters for testing the endpoints.

2023-07-19 19:40 UTC, rijuma commented on ai_aside/.DS_Store
Yes, just removed the file and added the entry to .gitignore

2023-07-19 19:40 UTC, rijuma commented on ai_aside/__init__.py
>  __version__ = '3.0.0'
Whoops!

2023-07-19 19:42 UTC, aethant commented
@rijuma  @ashultz0 to play devil's advocate here, and based on Andy's thread in Slack earlier, would it be beneficial to use string flags rather than booleans to account for 'gray areas' of summary enabling?

2023-07-19 19:48 UTC, ashultz0 requested changes
the structure is generally fine but there are a bunch of non-obvious things about how django queries work that we should change

haven't yet had a look at the tests, I wanted to get this core stuff marked first

2023-07-19 19:48 UTC, ashultz0 commented on ai_aside/api/urls.py
> +    path('v1/<course_id>/<unit_id>', UnitEnabledAPIView.as_view(), name='api-unit-settings'),
for these I think we usually use a more complicated URL regex - it amounts to the same thing but is more restricted

https://github.com/edx/edx-exams/blob/main/edx_exams/apps/api/v1/urls.py is an example though the patterns are off in https://github.com/edx/edx-exams/blob/main/edx_exams/apps/core/constants.py

there are probably also examples in edx-platform

2023-07-19 19:48 UTC, ashultz0 commented on ai_aside/api/views.py
> +        ).first()
we should only have one so it'd be acceptable to just select one object and error if there are two rather than filtering, I think that's objects.get or some similar name

if we are going to take first() we have to define how we are sorting or this could be unstable and confusing. It's probably better to just error when there is more than one.

2023-07-19 19:48 UTC, ashultz0 commented on ai_aside/api/views.py
> +        ).first()
same thing with first

2023-07-19 19:48 UTC, ashultz0 commented on ai_aside/api/views.py
> +        ).first()
ah it looks like the models have created as a default sort

I'd actually take that out since we usually should not care about sorting

2023-07-19 19:48 UTC, ashultz0 commented on ai_aside/api/views.py
> +            enabled=enabled,
I think to make this work right we have to update the model to tell it that course_key is a unique key, that way it can know that there already is one and it should update. Without that it might also take enabled into account so you could have two, or it might always create.

2023-07-19 19:48 UTC, ashultz0 commented on ai_aside/api/views.py
> +            enabled=enabled,
this has the update or create thing as above only it's course/unit unique together

2023-07-19 19:49 UTC, rijuma commented
> @rijuma @ashultz0 to play devil's advocate here, and based on Andy's thread in Slack earlier, would it be beneficial to use string flags rather than booleans to account for 'gray areas' of summary enabling?

Leaving a paper trail here, the issue is that not having an override on a module indicates that the enabled state is determined by the course, so for the modules we would have three states:
- enabled
- disabled
- inherited from the course
So the module record is considered as an override for the course.
I'll add the option to delete the record for removing the override.

2023-07-19 19:53 UTC, ashultz0 commented
> @rijuma @ashultz0 to play devil's advocate here, and based on Andy's thread in Slack earlier, would it be beneficial to use string flags rather than booleans to account for 'gray areas' of summary enabling?

Interesting... though since we are installing into a lack of settings, we're forced to handle the case without settings for courses and units no matter what field type we have here.

I was trying to feel out whether we're going to have a followup project that is about having different types of enabled summary-like thing but there is nothing on the radar so that won't be soon. That would be something like OFF/SUMMARIES/REVIEW_QUESTIONS/JOKES keying to different AI types. It felt like borrowing work to put it in now although we could just put it in at the DB layer and then expose just the boolean via the API, preventing a possible future migration.

2023-07-19 19:57 UTC, aethant commented
> > @rijuma @ashultz0 to play devil's advocate here, and based on Andy's thread in Slack earlier, would it be beneficial to use string flags rather than booleans to account for 'gray areas' of summary enabling?
> 
> Interesting... though since we are installing into a lack of settings, we're forced to handle the case without settings for courses and units no matter what field type we have here.
> 
> I was trying to feel out whether we're going to have a followup project that is about having different types of enabled summary-like thing but there is nothing on the radar so that won't be soon. That would be something like OFF/SUMMARIES/REVIEW_QUESTIONS/JOKES keying to different AI types. It felt like borrowing work to put it in now although we could just put it in at the DB layer and then expose just the boolean via the API, preventing a possible future migration.

Were it me - I would probably do something like `<TYPE>_<STATE1>`, `<TYPE>_<STATE2>`, and so on. Different potential tools may have different toggle states, even for the same content. A syllabus is only really valid, for example, at a higher level than an individual unit or lesson. In this case, you might have `SUMMARY_OFF` `SUMMARY_ON` `SUMMARY_INHERIT` or something. Then, too, you can always add new types down the road as new issues arise.

2023-07-19 19:57 UTC, ashultz0 commented
currently the only UX that removes the override is when the course level setting is changed it wipes all existing unit configs, so that could be embedded in the course level API call... but having it separate would be more reusable later. There is no UX for wiping a single unit at a time right now.

2023-07-19 20:05 UTC, ashultz0 commented
We can use multiple fields and migrate in a config type field later defaulted to summary to update all existing enabled/disabled into the right bucket when we have more buckets. We don't know much about future use cases so I'm reluctant to suggest more complexity.

2023-07-20 15:28 UTC, rijuma commented on ai_aside/api/urls.py
> +    path('v1/<course_id>/<unit_id>', UnitEnabledAPIView.as_view(), name='api-unit-settings'),
Thanks for the examples. After implementing the regex, effectively the "wrong key" test cases were useless, since course ids and unit ids with the wrong keys would not match the regex. I'm keeping the try/catch when parsing those in the implementation, despite me being unable to reach those cases through the tests. I feel a bit "safer" that way.

2023-07-20 17:54 UTC, rijuma commented on ai_aside/api/views.py
> +            enabled=enabled,
Added the `DELETE` http word for removing the override. Also updated the models to make sure we use unique rows for the settings.

2023-07-20 18:22 UTC, ashultz0 commented on ai_aside/migrations/0002_auto_20230720_1544.py
> +            options={},
I was trying to figure out why it was doing this and it must be removing the default sort 👍

2023-07-20 18:45 UTC, rijuma commented on ai_aside/migrations/0002_auto_20230720_1544.py
> +            options={},
Yeah, probably

2023-07-20 19:23 UTC, ashultz0 commented
please capture the description you have at the top of this PR in the repo somewhere - honestly just fleshing out the docstring at the top of the views file is probably as fancy as needed. Since you wrote it, let's not lose it :)

2023-07-20 19:25 UTC, ashultz0 commented on tests/test_api.py
> +        self.assertEqual(response.status_code, 404)
by adding the unique constraints we now have another useful case to test: that when you do a post with the same course_id or course_id/unit_id pair and a different enabled it does not create a new record

2023-07-21 13:44 UTC, rijuma commented on tests/test_api.py
> +        self.assertEqual(response.status_code, 404)
This is already there in the unit tests, for the "disabled" case I add a record as true and then run the endpoint to set it as false.

2023-07-21 13:54 UTC, ashultz0 commented on tests/test_api.py
> +        self.assertEqual(response.status_code, 404)
ah I see, I read too fast and missed that there was a direct create and a post, perfectly valid way to do it 👍

2023-07-21 13:55 UTC, ashultz0 approved these changes
let's ship it! Please capture your good doc but no need for more review

2023-07-21 14:31 UTC, merged