[ACADEMIC-16210] (WIP)
edx/ai-aside pull request #43
Opened 2023-07-25 19:16 UTC by rijuma

Separate API layer in its own module.

**Merge checklist:**
Check off if complete *or* not applicable:
- [ ] Version bumped
- [ ] Changelog record added
- [ ] Documentation updated (not only docstrings)
- [ ] Fixup commits are squashed away
- [ ] Unit tests added/updated
- [ ] Manual testing instructions provided
- [ ] Noted any: Concerns, dependencies, migration issues, deadlines, tickets

2023-07-26 20:16 UTC, ashultz0 requested changes
I have some random nitpicking comments about names and return values that honestly I don't care whether you take them or not.

The one thing that makes me hit request changes is that we do need the exposed API function and view and URL exposing the waffle flag to know if configuration is even allowed for the course.

2023-07-26 20:16 UTC, ashultz0 commented on ai_aside/api/api.py
> +"""
a trick you can do here is to put the api calls into __init.py__ inside the api directory, then you won't have api.api going on.

if you do that it would probably make sense to put just the public items in there and put the _get style internal methods in like api/internal.py

honestly I'm not a huge fan of putting a bunch of stuff in the __init.py__ but it is a very common practice

alternately, what if we called the api directory the config_api directory, that sets the context for the views and the api.py file

2023-07-26 20:16 UTC, ashultz0 commented on ai_aside/api/api.py
> +    "Gets the settings of a course"
since the get and set are using key/value dicts, you should describe the expected dicts in the docstring

2023-07-26 20:16 UTC, ashultz0 commented on ai_aside/api/api.py
> +    return True
this return value doesn't really mean anything so don't bother to return anything

2023-07-26 20:16 UTC, ashultz0 commented on ai_aside/api/api.py
> +    update = {'enabled': enabled}
same as in course

2023-07-26 20:16 UTC, ashultz0 commented on ai_aside/api/api.py
> +    return True
meaningless return

a common thing you could do instead is to return the same thing the GET would - so in this case the settings dict again - but that's still pretty meaningless. In the future case where you are updating only some settings it would be more useful to return the complete settings dict incorporating changes afterwards, but we only have the one

2023-07-26 20:16 UTC, ashultz0 commented on ai_aside/api/api.py
> +    return False
we need one more function in the API (and views) that just exposes summaries_configuration_enabled(course_key), since neither the course level or unit level settings should appear if that is not on

2023-07-26 20:26 UTC, ashultz0 commented on ai_aside/block.py
> +            return False
this clause should only trigger if the new flag is not on - we'll be retiring this old flag and replacing this with configuration, so it will start to be off everywhere. You could move this check into is_summary_enabled, something like:

`if summary config waffle is enabled for this course:
    check the config
otherwise if the old flag is enabled for this course:
    return true
return false`

2023-07-27 14:28 UTC, ashultz0 commented on ai_aside/api/api.py
> +    return False
added this to the PR to unblock David while Marcos is out sick so this should be all set

2023-07-28 14:40 UTC, rijuma commented on ai_aside/api/api.py
> +"""
I went for the `config_api` directory but keeping the `api.py`. Tried a few things and it went weird. I did move the `_get_*` methods to a different `internal.py` module.

2023-07-28 15:17 UTC, ashultz0 commented on requirements.txt
> +#
not sure how this file is here, requirements files are all in the requirements directory

2023-07-28 15:21 UTC, ashultz0 requested changes
actually I missed one needed logic change

2023-07-28 15:45 UTC, rijuma commented on ai_aside/config_api/api.py
> +        return True
Now that the `should_apply_to_block` is using it only when the waffle flag is enabled, any other uses of the method make sense to have it false if the flag is disabled. Updated.

2023-07-28 16:11 UTC, ashultz0 approved these changes
one comment to fix before merge but then good to go

2023-07-28 16:11 UTC, ashultz0 commented on ai_aside/config_api/api.py
> +    # If the feature flag is disabled, do not restrict
the code is updated but he comment isn't

2023-07-28 17:37 UTC, merged