feat: add studio write access validation
edx/ai-aside pull request #55
Opened 2023-08-29 20:10 UTC by germanolleunlp

# Add studio write access validation

### Ticket: https://jira.2u.com/browse/ACADEMIC-16359

**Merge checklist:**
Check off if complete *or* not applicable:
- [X] Version bumped
- [X] Changelog record added
- [X] Documentation updated (not only docstrings)
- [X] Fixup commits are squashed away
- [X] Unit tests added/updated
- [X] Manual testing instructions provided
- [X] Noted any: Concerns, dependencies, migration issues, deadlines, tickets

2023-08-29 20:45 UTC, ashultz0 requested changes
needs a changelog entry and update of version number, probably to 3.5.0

thoughts about organization you can take or leave

also it might need the decorator that actually requires and decodes a user on the view calls

2023-08-29 20:45 UTC, ashultz0 commented on ai_aside/platform_imports.py
> +    Check if the user can change the summaries settings.
worth putting "by checking for studio write access" in this comment

2023-08-29 20:45 UTC, ashultz0 commented on ai_aside/api/__init__.py
> +        Converts proctoring exceptions into standard restframework responses
copy error, should be aside exceptions

2023-08-29 20:45 UTC, ashultz0 commented on tests/api/test_views.py
> +has_studio_write_access = True
you only test the true case here

2023-08-29 20:45 UTC, ashultz0 commented on tests/api/test_views.py
> +        auth_mock.has_studio_write_access = fake_has_studio_write_access
I think there are mock methods where you can say auth_mock.has_studio_write_access is a method that returns true, then you don't need the fake and it would be easy to test the negative case too

2023-08-29 20:45 UTC, ashultz0 commented on ai_aside/config_api/views.py
> +    permission_classes = (HasStudioWriteAccess,)
I think you also need to add the jwt auth decorator or the endpoint won't have decoded the user. But I might be wrong.

have you tested this locally yet?

2023-08-29 20:45 UTC, ashultz0 commented on ai_aside/api/view_utils.py
> +        ValidationError: DRF Validation error in case the unit key is invalid
this comment isn't the way it works here, wrong error type

also a very wordy style of docstring, not my favorite but fine if you want it

2023-08-29 20:45 UTC, ashultz0 commented on ai_aside/api/view_utils.py
> +Utilities related to API views
this file is actually just validators.py

unless you take the stuff in init and put it in here which might be nice, things often get missed in init.py

2023-08-29 20:45 UTC, ashultz0 commented on ai_aside/api/__init__.py
> +"""
we don't have a generic api directory right now and this stuff is all specific to the config api, I think it goes down at that level rather than generalizing to the overall API we don't have

2023-08-29 20:45 UTC, ashultz0 commented on ai_aside/api/permissions.py
> +""" Permissions for ai-aside API"""
this one is especially config-api specific

2023-09-01 19:33 UTC, germanolleunlp commented on ai_aside/platform_imports.py
> +    Check if the user can change the summaries settings.
✅

2023-09-01 19:33 UTC, germanolleunlp commented on ai_aside/api/__init__.py
> +        Converts proctoring exceptions into standard restframework responses
✅

2023-09-01 19:34 UTC, germanolleunlp commented on ai_aside/config_api/views.py
> +    permission_classes = (HasStudioWriteAccess,)
I tested it locally, and it was working without the `Jwt` decorator

2023-09-01 19:40 UTC, germanolleunlp commented on ai_aside/config_api/views.py
> +    permission_classes = (HasStudioWriteAccess,)
and it has the user 👍🏽

2023-09-01 19:54 UTC, germanolleunlp commented on ai_aside/api/view_utils.py
> +        ValidationError: DRF Validation error in case the unit key is invalid
✅

2023-09-01 19:55 UTC, germanolleunlp commented on ai_aside/api/view_utils.py
> +Utilities related to API views
✅

2023-09-01 19:55 UTC, germanolleunlp commented on ai_aside/api/__init__.py
> +"""
removed and moved it to `config_api`

2023-09-01 19:55 UTC, germanolleunlp commented on ai_aside/api/permissions.py
> +""" Permissions for ai-aside API"""
✅

2023-09-04 13:17 UTC, germanolleunlp commented on tests/api/test_views.py
> +has_studio_write_access = True
✅

2023-09-04 13:17 UTC, germanolleunlp commented on tests/api/test_views.py
> +        auth_mock.has_studio_write_access = fake_has_studio_write_access
✅ replaced with @patch

2023-09-04 14:30 UTC, germanolleunlp commented
> needs a changelog entry and update of version number, probably to 3.5.0
> 
> thoughts about organization you can take or leave
> 
> also it might need the decorator that actually requires and decodes a user on the view calls

💹  done

2023-09-05 14:02 UTC, ashultz0 commented on tests/api/test_views.py
> +        self.access_mock.start()
this is a weird python resource leak technicality

in super.setup it makes self.accessmock and starts it, let's call that mock1
then here you reassign self.accessmock to a new mock and start it, that's mock2
there is no longer any reference available to mock1, self.accessmock is now mock2

in teardown we tear down mock2. mock1 is never torn down.

I don't think that mocks really leak anything significant especially if you never start them so this is just something to notice. Fixing it would just be not calling super setup or delegating mock creation into a function which reads self.can_change_summaries or a million other methods.

2023-09-06 13:00 UTC, germanolleunlp commented on tests/api/test_views.py
> +        self.access_mock.start()
Thanks!

2023-09-06 13:01 UTC, merged